### ISSUE TITLE
Herbeeeert

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/ansible-config#105]
- [x] config ansible for herbert (@silox)
- [x] config herbert for ansible (@silox)
- [x] add rocket.chat on herbert
  - [x] user (@silox)
  - [x] role (@silox)
  - [ ] request a share (@redfast00 @rien ? someone from ugent anyway :D)
  - [x] fix oauth (@silox)
- [ ] abyss

**Comment by NoctuaNivalis** [comment]
> request a share

me mee meeeeeee

**Comment by NoctuaNivalis** [comment]
well, tomorrow.

**Comment by redfast00** [comment]
@NoctuaNivalis chat.zeus.gent is live!

**Comment by NoctuaNivalis** [comment]
I was already attempting to log in ;-)

**Comment by NoctuaNivalis** [comment]
So I tried to request a share through the standard form. However, it mentioned only ghent university _employees_ could be given access. You'll probably have to mail for an exception.

**Comment by rien** [comment]
We already have been granted shares for FK-Enrollment and for Bottlebats, so I think if we ask nicely they may give use another one.
