### ISSUE TITLE
Move away from king so we can reinstall it

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/ansible-config#133]
# 12urenloop

- [x] factuur.12urenloop.be https://github.com/12urenloop/factuur
- [x] 12urenloop.be (static site)
- [x] join.12urenloop.be https://github.com/12urenloop/join-site
- [x] live.12urenloop.be https://github.com/12urenloop/boxxy
- [x] materiaal.12urenloop.be https://github.com/zeuswpi/saruman

# FK

- [x] event.fkgent.be https://github.com/ZeusWPI/Gandalf

# Zeus

- [x] zeus.gent, zeus.ugent.be https://github.com/zeus/zeuswpi (static site)
- [x] wiki (mediawiki)
- [x] Gamification (TODO: write docker for prod)
- [x] ZEUSWPI (the image uploading thing)
- [x] slackintegrations (yeet?)
- [x] mailman

## Hydra

- [x] static site
- [x] API
- [X] google assistant (yeeted)

# GSR

- [x] stuw.ugent.be
- [x] gentsestudentenraad.be
- [x] stuver18.be

# Third party

- [x] macht.ugent.be
- [x] ceneka.ugent.be

**Comment by xerbalind** [comment]
is reinstalled
