### ISSUE TITLE
Make Zauth registration subscribe you to the mailing list again

### ISSUE THREAD

**Issue by redfast00** [ZeusWPI/ansible-config#150]
Before Zauth, the script to add a user would also add the email address of that user to the mailing list. This has not been implemented yet, so now when approving a new user, we have to not forget to also add the email address to the mailing list. Zauth already has an option to send new user registrations to a webhook, but nothing has been written to catch this webhook and make it add a user to the mailingllist.

**Comment by FKD13** [comment]
NoNo move the mailinglist to Zauth
