### ISSUE TITLE
Switch to mailman 3.1 when it's there, or to an alternative

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/ansible-config#34]

**Comment by Procrat** [comment]
When this issue was made, Mailman 3.0 had been released but no migration script or even strategy from v2 was in place yet. They claimed it would happen with v3.1. I see in the docs that you can do a semi-automated migration now ([link 1](https://docs.mailman3.org/en/latest/migration.html) and [link 2](https://docs.mailman3.org/en/latest/upgrade-3.2.html)).

**Comment by redfast00** [comment]
We won't be using mailman again

**Comment by Procrat** [comment]
Oooh, what are you going to migrate to?

**Comment by redfast00** [comment]
We've built our own minimal mailing list in Zauth

**Comment by Procrat** [comment]
Fancy! Probably cleaner than the funky piece of software that mailman is :D
