### ISSUE TITLE
Remove mediawiki when dokuwiki has been installed

### ISSUE THREAD

**Issue by FlashYoshi** [ZeusWPI/ansible-config#45]
Things to remove:
- [x] `mediawiki` mysql database (leave, see comment)
- [x] `mediawiki` mysql user (leave, see comment)
- [x] `/var/lib/mediawiki` (moved and deleted)
- [x] `/usr/share/mediawiki` (moved and deleted)
- [x] `/home/dokuwiki/MediaWiki-to-DokuWiki-Importer`

**Comment by Silox** [comment]
@FlashYoshi So, is Dokuwiki fully installed? Can I perform the actions from the first post?

**Comment by JensTimmerman** [comment]
don't delete things, archive them!

**Comment by Silox** [comment]
We have backups, this is about system files :)

**Comment by FlashYoshi** [comment]
Should be fine yes

**Comment by Silox** [comment]
Done
