### ISSUE TITLE
Backup restore script / checklist

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/ansible-config#49]
Now that the migration is fresh in memory, we should soon write a backup script or a checklist.
Inspiration can be extracted from #27 and #43.

**Comment by Procrat** [comment]
I think the following ought to be restored:
- /home/: I think it's best we restore everything. At the very least:
  - .ssh/ of every user
  - .forward of every user
  - the full home dir of every app that isn't a git repo
  - For Rails apps: secrets.yml, database.yml and public/shared files? (Don't know how those things are called.)
- /root/
- /var/spool/cron/
- /var/lib/mailman/
- /var/log/ (can be argued about whether this is necessary)
- /tmp/database_dumps/

/etc/ also gets backed up by Abyss, but shouldn't be part of the restore script as this is completely handled by Ansible.

Does this cover everything?

**Comment by FlashYoshi** [comment]
Logs don't necessarily need to be restored but backing them up seems mandatory to me.
Shouldn't we also restore the databases that abyss, probably, backs up?

**Comment by Procrat** [comment]
You're right. Removed /var/log/.

I already mentioned /tmp/database_dumps/: that's where the databases are backed up.

**Comment by FlashYoshi** [comment]
#43 mentions `hydra api history`, it this just in hydra's home folder?

**Comment by Silox** [comment]
@FlashYoshi Yes

**Comment by redfast00** [comment]
We use borg now, with a good config
