### ISSUE TITLE
Check out sensitive data

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/ansible-config#53]
I deleted some stuff (also from the git history):

- ssl keys from nginx_configs/files/ssl: Is this backup data? Do we put this in the vault? In any case, regenerate them
- rsysmond license key: I put it in the vault, but the template file should be readded

**Comment by FlashYoshi** [comment]
The IPTables ports should be added to the vault as well.

**Comment by Silox** [comment]
We'll also need to change all ports from all configuration files to use the vault ports in that case.

**Comment by FlashYoshi** [comment]
Not really, I don't think we should do anything about our local ports, just the public ones, which are only defined once. But apparently even that is not worth the effort.

**Comment by FlashYoshi** [comment]
Ssl keys and the like are backup material. All the sensitive information has been removed and new keys have been acquired, thus this can be closed.

**Comment by Procrat** [comment]
I'd say SSL keys are Ansible material?
