### ISSUE TITLE
Create a matrix user.

### ISSUE THREAD

**Issue by NoctuaNivalis** [ZeusWPI/ansible-config#57]
To solve #51, I'm in need of a matrix user. I've noted that there exists a dokuwiki user but I seem unable to find it's origin. Could anyone explain to me how I should add users to ansible?

**Comment by FlashYoshi** [comment]
Users are added by ansible with the `users` role. Which users are made, what their password is and what other properties they possess is configured in the ansible vault. As you can not access this vault I will add the matrix user for you.

**Comment by FlashYoshi** [comment]
Fixed in fa5a4f97a7e9076840c79a3baf05fad386ade63f
