### ISSUE TITLE
chown: invalid user: 'cultour:crontab'

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/ansible-config#72]
Somewhere a faulty cron?

**Comment by Procrat** [comment]
When/where did this occur?

**Comment by Silox** [comment]
After updating the `cron` package

**Comment by Silox** [comment]
I can't reproduce it by restarting `cron` though.

**Comment by Procrat** [comment]
Removed obsolete `/var/spool/cron/crontabs/cultour`.
