### ISSUE TITLE
Verne upgrade stuff

### ISSUE THREAD

**Issue by Silox** [ZeusWPI/ansible-config#74]
- [x] Check /etc/grub.d/10_linux (is created, no old version) but /etc/grub.d/50_linux is still there?

Seems like this is required for Xen, conclusion: move 10_linux to 50_linux (source: https://lists.debian.org/debian-user/2013/04/msg00190.html)
- [ ] Set the ssh password authentication off (I put it on temporarily in the upgrade)
- [x] Check out `/etc/sysctl.conf` (kept old version), we should put this changed default shit in the `/etc/sysctl.d/` folder

**Comment by NoctuaNivalis** [comment]
- [ ] reboot

**Comment by Silox** [comment]
- [ ] checkout nut (I changed the config too late, so perhaps just rebooting the service should fix it)

**Comment by Silox** [comment]
- [ ] put our values in the new xen-tools.conf, mv the new over the current

**Comment by Silox** [comment]
- [ ] check out nut again
```
May  4 22:00:39 verne systemd[1]: nut-driver.service: control process exited, code=exited status=1
May  4 22:00:39 verne systemd[1]: Failed to start Network UPS Tools - power device driver controller.
May  4 22:00:39 verne systemd[1]: Dependency failed for Network UPS Tools - power devices information server.
May  4 22:00:39 verne systemd[1]: Unit nut-driver.service entered failed state.
```

**Comment by Silox** [comment]
- [ ] check out fail2ban
```
May  4 22:00:45 verne fail2ban[1331]: Starting authentication failure monitor: fail2banERROR  Failed during configuration: File contains no section headers.
May  4 22:00:45 verne fail2ban[1331]: file: /etc/fail2ban/jail.d/verne.conf, line: 1
May  4 22:00:45 verne fail2ban[1331]: 'destemail = admin@zeus.ugent.be\n'
May  4 22:00:45 verne fail2ban[1331]: failed!
```

**Comment by NoctuaNivalis** [comment]
- [ ] reboot

**Comment by redfast00** [comment]
Verne is dood
