### ISSUE TITLE
Zeus accounts: homemade or LDAP?

### ISSUE THREAD

**Issue by R13N** [ZeusWPI/ansible-config#87]
Nu we onze servers aan het migreren zijn naar _de cloud_ en eigenlijk de infrastructuur gedeeltelijk aan het refactoren zijn, dringt de vraag zich op in hoeverre het huidige systeem voldoet aan onze noden. De configuratie die nu draait is opgesteld geweest om te werken met clients. Aangezien iedereen de dag van vandaag zijn eigen laptop meebrengt (en er geen clients in de kelder meer staan) wordt het misschien tijd voor een nieuwe aanpak.

Onze huidige configuratie is de volgende:
- LDAP met accountnaam, email, userid, ...
- Kerberos regelt authenticatie
- AFS (Andrew File System) houdt de bestanden van gebruikers bij

AFS kunnen we sowieso dumpen. Het brengt enkel maar extra complexiteit met zich mee en het heeft geen extra features die we niet hebben met een normaal bestandssysteem (eventueel met quota en een optioneel geëncrypteerd deel met [encfs](https://github.com/vgough/encfs)).

Kerberos lijkt ons ook te complex voor onze huidige situatie.

Een eerste optie is om LDAP ook de authenticatie te laten regelen. Eventueel een kleine webapplicatie rond deze LDAP te voorzien om wachtwoorden te resetten en informatie aan te passen.

Een andere optie die @werthen voorstelt is Kerberos en LDAP te vervangen door een eigen systeem: een webapplicatie waarin we accounts opslaan en authenticatie regelen. Hier hebben we het meeste controle over welke features we willen en we zijn ervan overtuigd dat dit relatief vlug geschreven kan zijn (vb: rails met devise). Een nadeel van deze optie is dat we zelf gaan moeten de integratie met alles regelen: een eigen PAM-module schrijven, OAuth fixen en deftige beveiliging voorzien. Maar dit lijkt mij best nog doenbaar.

Wat zijn jullie meningen?

**Comment by Silox** [comment]
👎 voor zelf schrijven, security hazard + veel meer werk dan je op het eerste zich zou denken

**Comment by itkovian** [comment]
Gelet op het feit dat je impliciet toegang geeft tot het UGentNet, zou ik _zeer_ voorzichtig zijn om zelf iets op te zetten. Je kunt beter tested en proven tech gebruiken waar mensen effectief security patches voor uitbrengen.

**Comment by R13N** [comment]
Alle accounts zijn u ongeveer gemigreerd naar adams, zelfde setup. Nu nog userdirs en shell access.
