### ISSUE TITLE
ZeusnetV2

### ISSUE THREAD

**Issue by rien** [ZeusWPI/ansible-config#88]
Migrate all the services to _the cloud_ !

### Adams:
- [x] Migrate kerberos to adams
- [x] Migrate ldap to adams
- [x] Migrate mails to adams
- [ ] Migrate nginx sites to adam (phpldapadmin, ntop, ...)
- [ ] Backup adams
- [ ] Create fancy account pages (change pw, change email, ...)

### Kelder
- [ ] Replace verne with an other router (dick)
- [ ] Fix redirects
- [ ] Backup router

### Gygax
- [ ] Install (Arch Linux?)
- [ ] Fix user logins
- [ ] Fix userdirs
- [ ] Fix public userdirs

### External sites
- [ ] Request VM
- [ ] Install VM
- [ ] Migrate all the sites:
    - stuw.ugent.be
    - gsr.ugent.be
    - macht.ugent.be
    - ceneka.ugent.be
    - ... (???)

**Comment by redfast00** [comment]
This is pretty outdated now
