### ISSUE TITLE
Nice to have: slack callbacks

### ISSUE THREAD

**Issue by rien** [ZeusWPI/ansible-config#92]
See what has changed on slack.
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/slack.py

**Comment by R13N** [comment]
Thanks to @Procrat for bringing this up! :smile:

**Comment by Procrat** [comment]
Just to be clear: These callback plugins are configured in your `ansible.cfg`, so it is part of the user configuration, not of the playbook.

The other plugin I mentioned was [this one](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/callback/profile_tasks.rst), which allows you to see the bottlenecks in your playbook after a run.

**Comment by Procrat** [comment]
Oops, I was wrong. You can have an `ansible.cfg` in your playbook.
